TinTuc/Controllers/CategoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TinTuc.Models;

namespace TinTuc.Controllers
{
    public class CategoryController : Controller
    {
        private TinTucEntities db = new TinTucEntities();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.DMBanTins.ToList());
        }
        public ActionResult CatePartial()
        {
            return PartialView();
        }
        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TenDM")] DMBanTin dMBanTin)
        {
            if (ModelState.IsValid)
            {
                db.DMBanTins.Add(dMBanTin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dMBanTin);
        }
        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DMBanTin dMBanTin = db.DMBanTins.Find(id);
            db.DMBanTins.Remove(dMBanTin);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TinTuc/Controllers/CustomerController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TinTuc.Models;

namespace TinTuc.Controllers
{
    public class CustomerController : Controller
    {
        private TinTucEntities db = new TinTucEntities();

        // GET: Customer
        public ActionResult Index()
        {
            return View(db.NguoiDungs.ToList());
        }
        // POST: Customer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.NguoiDungs.Add(nguoiDung);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(nguoiDung);
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }

            return View(nguoiDung);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            db.NguoiDungs.Remove(nguoiDung);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Logout()
        {
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }
    }
}

TinTuc/Controllers/NewsController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TinTuc.Models;

namespace TinTuc.Controllers
{
    public class NewsController : Controller
    {
        private TinTucEntities db = new TinTucEntities();

        // GET: News
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
                var banTins = db.BanTins.Include(b => b.Admin).Include(b => b.DMBanTin);

                return View(banTins.ToList());
            }
            
            return RedirectToAction("Index", "Admin");
        }
        // GET: News/Create
        public ActionResult Create()
        {
            if (Session["Admin"] != null)
            {
                ViewBag.TKAdmin = new SelectList(db.Admins, "UserName", "UserName");
                ViewBag.MaDM = new SelectList(db.DMBanTins, "ID", "TenDM");

                return View();
            }

            return RedirectToAction("Index", "Admin");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BanTin banTin = db.BanTins.Find(id);
            if (banTin == null)
            {
                return HttpNotFound();
            }
            ViewBag.TKAdmin = new SelectList(db.Admins, "UserName", "UserName", banTin.TKAdmin);
            ViewBag.MaDM = new SelectList(db.DMBanTins, "ID", "TenDM", banTin.MaDM);

            return View(banTin);
        }
        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(BanTin banTin)
        {
            banTin.TKAdmin = Session["Admin"].ToString().Trim();
            banTin.SoSao = 0;
            banTin.Admin = db.Admins.FirstOrDefault(k => k.UserName == banTin.TKAdmin);
            if (ModelState.IsValid)
            {
                if(banTin.UploadImage != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(banTin.UploadImage.FileName);
                    string extension = Path.GetExtension(banTin.UploadImage.FileName);
                    fileName += extension;
                    banTin.HinhAnh = fileName;
                    banTin.UploadImage.SaveAs(Path.Combine(Server.MapPath(BanTin.SERVER_IMG_PATH), fileName));
                }
                db.BanTins.Add(banTin);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.TKAdmin = new SelectList(db.Admins, "UserName", "UserName", banTin.TKAdmin);
            ViewBag.MaDM = new SelectList(db.DMBanTins, "ID", "TenDM", banTin.MaDM);

            return View(banTin);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                BanTin banTin = db.BanTins.Find(id);
                if (banTin == null)
                {
                    return HttpNotFound();
                }
                ViewBag.TKAdmin = new SelectList(db.Admins, "UserName", "UserName", banTin.TKAdmin);
                ViewBag.MaDM = new SelectList(db.DMBanTins, "ID", "TenDM", banTin.MaDM);

                return View(banTin);
            }

            return RedirectToAction("Index", "Admin");
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BanTin banTin)
        {
            banTin.TKAdmin = Session["Admin"].ToString().Trim();
            banTin.SoSao = 0;
            banTin.Admin = db.Admins.FirstOrDefault(k => k.UserName == banTin.TKAdmin);
            if (ModelState.IsValid)
            {
                if (banTin.UploadImage != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(banTin.UploadImage.FileName);
                    string extension = Path.GetExtension(banTin.UploadImage.FileName);
                    fileName += extension;
                    banTin.HinhAnh = fileName;
                    banTin.UploadImage.SaveAs(Path.Combine(Server.MapPath(BanTin.SERVER_IMG_PATH), fileName));
                }
                db.Entry(banTin).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.TKAdmin = new SelectList(db.Admins, "UserName", "UserName", banTin.TKAdmin);
            ViewBag.MaDM = new SelectList(db.DMBanTins, "ID", "TenDM", banTin.MaDM);

            return View(banTin);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                BanTin banTin = db.BanTins.Find(id);
                if (banTin == null)
                {
                    return HttpNotFound();
                }

                return View(banTin);
            }

            return RedirectToAction("Index", "Admin");
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BanTin banTin = db.BanTins.Find(id);
            db.BanTins.Remove(banTin);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TinTuc/Views/Admin/Index.cshtml
@model TinTuc.Models.Admin
@{
    ViewBag.Title = "Đăng nhập Quản trị viên";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="section">
    <h2 class="text-center text-uppercase mt-3 mb-3">Đăng nhập Quản trị viên</h2>
    <div class="container-fluid">
        <div class="col">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    @using (Html.BeginForm("Login", "Admin"))
                    {
                        @Html.AntiForgeryToken()
                        <div class="mb-3">
                            <label for="UserName" class="mb-2">Tài khoản: </label>
                            <input type="text" name="UserName" class="form-control" />
                        </div>
                        <div class="mb-3">
                            <label for="Password" class="mb-2">Mật khẩu: </label>
                            <input type="password" name="Password" class="form-control" />
                        </div>
                        <div class="mb-3 text-center">
                            <input type="submit" value="Đăng nhập" class="btn btn-outline-success" />
                        </div>
                    }
                    <p class="text-center text-danger mt-3 mb-3 text-center">@ViewBag.Error</p>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
</section>

TinTuc/Views/Admin/Manager.cshtml
@{
    ViewBag.Title = "Quản trị Website";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="section">
    <h2 class="text-center text-uppercase">Menu Quản trị viên</h2>
    <h5 class="mt-5 text-center">Chọn menu bên trái để thực hiện chức năng</h5>
</section>

TinTuc/Views/Admin/Toolbox.cshtml
<ul class="nav-links">
    <li>
        <div class="iocn-link fs-6">
            <a href="@Url.Action("Index", "Customer")">
                <!-- Icon -->
                <i class='bx bxs-calendar-event'></i>
                <!-- Tên -->
                <span class="link_name">Người dùng</span>
            </a>
        </div>
    </li>
    <li>
        <div class="iocn-link fs-6">
            <div class="link">
                <a href="@Url.Action("Index", "News")">
                    <!-- Icon -->
                    <i class='bx bxs-calendar-event'></i>
                    <!-- Tên -->
                    <span class="link_name">Bản tin</span>
                </a>
            </div>
        </div>
    </li>
    <li>
        <div class="iocn-link fs-6">
            <div class="link">
                <a href="@Url.Action("Index", "Category")">
                    <!-- Icon -->
                    <i class='bx bxs-calendar-event'></i>
                    <!-- Tên -->
                    <span class="link_name">Danh mục</span>
                </a>
            </div>
        </div>
    </li>
</ul>   