TinTuc/Controllers/LoginController.cs
using System.Linq;
using System.Web.Mvc;
using TinTuc.Models;

namespace TinTuc.Controllers
{
    public class LoginController : Controller
    {
        private TinTucEntities db = new TinTucEntities();

        // GET: Login
        public ActionResult Index() => View();
        public ActionResult Register() => View();

        // POST: Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(NguoiDung user)
        {
            try
            {
                string authTmp = SHA256.ToSHA256(user.Password);
                NguoiDung checkLogin = db.NguoiDungs.FirstOrDefault
                (
                    k => k.UserName == user.UserName && k.Password == authTmp
                );
                if(checkLogin != null )
                {
                    Session["Customer"] = checkLogin.TenND;

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.UserError = "Sai thông tin đăng nhập!";

                    return View("Index");
                }
            }
            catch
            {
                ViewBag.UserError = "Lỗi hệ thống!";

                return View("Index");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(NguoiDung user)
        {
            try
            {
                string authTmp = SHA256.ToSHA256(user.Password);
                user.Password = authTmp;
                if (ModelState.IsValid)
                {
                    db.NguoiDungs.Add(user);
                    db.SaveChanges();

                    return RedirectToActionPermanent("Index");
                }
                else
                {
                    ViewBag.UserError = "Lỗi hệ thống!";

                    return View();
                }
            }
            catch
            {
                ViewBag.UserError = "Lỗi hệ thống!";

                return View();
            }
        }
    }
}

TinTuc/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Sports News</title>
    @* CSS File *@
    <link rel="stylesheet" href="~/Resources/CSS/Manager.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @* Icon *@
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    @*Scripts of RTB editor*@
    @*<script src="https://cdn.tiny.cloud/1/6bfd78k4al1msrco9k23xq5o1j8vznv2mo8y7jof96klryli/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>*@
</head>

    <body>
        @* Thanh điều hướng *@
        <div class="sidebar">
            <img src="~/Resources/Images/Logo/sports-logo.png" id="logoImg" width="60" height="60" />
            @* Chức năng (Chuyển trang) *@
            @if (Session["Admin"] != null)
            {
                @Html.Action("Toolbox", "Admin")
                <!--Thông tin người dùng-->
                <div class="profile-content">
                    <div class="profile">
                        <a href="#" class="fs-6 text-decoration-none text-white">
                            <div class="profile-details">
                                <!-- Hình người dùng-->
                                <i class='bx bx-user' id="userImg"></i>
                                <!-- Thông tin -->
                                <div class="name-job">
                                    <!-- Họ tên -->
                                    <div class="name">@Session["Admin"].ToString()</div>
                                    <!-- Chức vụ -->
                                    <div class="job">Quản trị viên</div>
                                </div>
                            </div>
                        </a>
                        <!-- Đăng xuất -->
                        <a href="@Url.Action("Logout", "Admin")">
                            <i class='bx bx-log-out' style='color:#ffffff' id="log_out"></i>
                        </a>
                    </div>
                </div>
            }
            else
            {
                <!--Thông tin người dùng-->
                <div class="profile-content">
                    <div class="profile">
                        <div class="profile-details">
                            <a href="@Url.Action("Index", "Admin")" class="text-decoration-none fs-6 text-white">
                                <!-- Hình người dùng-->
                                <i class='bx bx-user' id="userImg"></i>
                                <!-- Thông tin -->
                                <div class="name-job">
                                    <!-- Họ tên -->
                                    <div class="name">Đăng nhập</div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
        @* Nội dung trang *@
        <div class="home-content">
            @RenderBody()
        </div>

        <script src="~/Resources/JavaScript/managerNavBar.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

TinTuc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sport News</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <a href="http://localhost:53197/">
            <img src="~/IMG/LogoSportNews.png" style="width:auto; height:200px;margin-left:70px;" />
        </a>
    </header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand">

            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tin mới nhất", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Thể thao", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Bảng xếp hạng", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="navbar-nav d-flex flex-row-reverse">
                    @if (Session["Customer"] == null)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Login")" class="nav-link">Đăng nhập</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Logout", "Customer")" class="nav-link">Đăng xuất</a>
                        </li>
                        <li>
                            <a href="#" class="nav-link" disabled>Xin chào, @Session["Customer"].ToString()</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Mạng xã hội:</span>
            </div>
            <!-- Left -->
            <!-- Right -->
            <div class="social-network" style="margin-right:850px;">
                <a href="" class="me-4 text-reset">
                    <i class="social-nav__link-icon social-nav__link--twitter-icon"></i>
                </a>
                <a href="https://www.facebook.com/profile.php?id=100087669636851" class="me-4 text-reset">
                    <i class="zmdi zmdi-facebook-box"></i>
                </a>
                <a href="#" class="me-4 text-reset">
                    <i class="zmdi zmdi-twitter-box"></i>
                </a>
                <a href="#" class="me-4 text-reset">
                    <i class="zmdi zmdi-instagram"></i>
                </a>
                <a href="https://github.com/simonp202" class="me-4 text-reset">
                    <i class="zmdi zmdi-github-alt"></i>
                </a>
            </div>
        </section>
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Sport News
                        </h6>
                        <p>
                            Chịu trách nhiệm nội dung: Phạm Minh Khánh & Nguyễn Trí
                            Sport News phát triển bởi HUFLIT Yêu Thể Thao.
                        </p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Liên Quan
                        </h6>
                        <p>
                            <a href="https://www.bongda.com.vn/" class="text-reset">Bongda</a>
                        </p>
                        <p>
                            <a href="https://www.skysports.com/" class="text-reset">Sky Sports</a>
                        </p>
                        <p>
                            <a href="https://thethao247.vn/" class="text-reset">THỂ THAO 247</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Liên hệ
                        </h6>
                        <p>
                            <a href="" class="text-reset">HOTLINE: 0373040869</a>
                        </p>
                        <p>
                            <a href="https://www.facebook.com/profile.php?id=100087669636851" class="text-reset">ADMIN</a>
                        </p>
                    </div>
                   </div>
            </div>
        </section>

        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="https://www.facebook.com/groups/k27.huflit.cntt">IT HUFLIT</a>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>